### ISSUE TITLE
Spark Streaming - terminated with exception: Could not get the id of the latest version for subject

### ISSUE THREAD

**Issue by ramvalasa** [AbsaOSS/ABRiS#101]
Hi, I am facing exception while trying to get latest version of schema version for subject even though it exists using spark streaming. This is not happening always, but i believe when the schema registry server is momentarily down for just few seconds/milliseconds.

Thinking of adding a retry logic to overcome the issue. Here are the few exceptions around it.

terminated with exception: Could not get the id of the latest version for subject "dummy_topic-value"

terminated with exception: Job aborted due to stage failure: Task 2 in stage 23483.0 failed 4 times, most recent failure: Lost task 2.3 in stage 23483.0 (TID 122887,, executor 105): avro.read.SchemaManagerException: Could not get the id of the latest version for subject 'dummy_topic-value'
Adjusted code change. Please suggest if there is any better way.

SchemaManager.Scala
```
    def getLatestVersionId(subject: String): Int = {
      logDebug(s"Trying to get latest schema version id for subject '$subject'")
      throwIfClientNotConfigured()

      getIDRetry(3) { schemaRegistryClient.getLatestSchemaMetadata(subject).getId }

/*      Try(schemaRegistryClient.getLatestSchemaMetadata(subject).getId) match {
        case Success(id) => id
        case Failure(e) => throw new SchemaManagerException(
          s"Could not get the id of the latest version for subject '$subject'", e)
      }*/
    }

  @annotation.tailrec
  def getIDRetry[T](n: Int)(fn: => T): T = {
    util.Try { fn } match {
      case util.Success(x) => x
      case _ if n > 1 => retry(n - 1){println("Tried fetching latest Schema id " + n + "times");Thread.sleep(10000); fn}
      case util.Failure(e) => throw e
    }
  }
```

**Comment by cerveada** [comment]
Hello, this looks good, but your code doesn't throw the `SchemaManagerException` with the informative message in case of failure.

It would be also good to use retry for other schema registry communication not only id, there is also some loading schema method and storing schema method if I remember correctly. Otherwise, you will fix only part of the problem.

Don't be afraid to create a pull request, so we can do a proper code review and potentially make it a part of next Abris release.

**Comment by felipemmelo** [comment]
Hi @ramvalasa , how are you?

We gave this issue a lot of thought recently as we're preparing a new release. We think that adding a retry to schema retrieval could cause more harm than good because there are other parameters that could be affected (e.g. Spark timeouts). 

On the other hand, we might not be seeing the whole thing, and if that is the case, we are entirely open to receive PRs if you have ideas.

Cheers.
