### ISSUE TITLE
Multiple sources found for json Spark 3.0.0

### ISSUE THREAD

**Issue by Braamling** [AbsaOSS/ABRiS#147]
Hey!

I'm using ABRiS in combination with Spark 3.0.0. Everything seems to work perfectly fine, except when I'm trying to use sources such as JSON and CSV. Somehow there seem to be conflicting dependencies between spark-sql-kafka and ABRiS. 

I'm loading the two packages as follows. 

```bash
pyspark --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.0.0,za.co.absa:abris_2.12:3.2.1
```

Reading a json input stream results in the following exception. Without the ABRiS package as a dependency, the code works fine. 

```bash
>>> df = spark.readStream.schema(stream_schema).json("/tmp/output.json")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/spark/python/pyspark/sql/streaming.py", line 531, in json
    return self._df(self._jreader.json(path))
  File "/opt/spark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1305, in __call__
  File "/opt/spark/python/pyspark/sql/utils.py", line 137, in deco
    raise_from(converted)
  File "<string>", line 3, in raise_from
pyspark.sql.utils.AnalysisException: Multiple sources found for json (org.apache.spark.sql.execution.datasources.v2.json.JsonDataSourceV2, org.apache.spark.sql.execution.datasources.json.JsonFileFormat), please specify the fully qualified class name.;
```

Any ideas on how to easily resolve this?

**Comment by Braamling** [comment]
Not ideal, but I have found a temporary workaround. Instead of using the `.json` method, I can also specify the datasource class specifically as the format. 

```python
    df = (
        spark
        .readStream
        .schema(stream_schema)
        .format("org.apache.spark.sql.execution.datasources.json.JsonFileFormat")
        .load("path_to_stream_directory")
    )
```

For now this has solved my problems. I still think the issue is relevant though :)

**Comment by felipemmelo** [comment]
Hi @Braamling , this probably is actually unrelated to ABRiS, it is about how Spark discovers and loads data sources from the class path. As the error message suggests, there are multiple implementations of the JSON data source, so you have to specify one. 

If you don't wanna do it hardcoded (which, personally, I don't think is an big issue), you can create the file `resources/META-INF/services/org.apache.spark.sql.sources.DataSourceRegister` and write the path to your preferred Json data source there.

Since this problem is not related to the library, I'll close this issue, but feel free to re-open it if needed.

Cheers.
