### ISSUE TITLE
How can I use 'subscribePattern' with avro schema?

### ISSUE THREAD

**Issue by suchitgupta01** [AbsaOSS/ABRiS#164]
Hi Team,
I am using spark structured streaming with subscribePattern and have a single job listening to multiple topics. 

So I have topics with naming strategy as below:

1. test.payload_1
2. test.payload_2

The payload fo the topics is wrapped inside "value_json".

Example payload for topic "test.payload_1"
```
{
   "value_json":{
      "key_a":"123",
      "key_b":"234"
   }
}
```

Example payload for topic "test.payload_2"
```
{
   "value_json":{
      "key_1":"abcc",
      "key_2":"deff"
   }
}
```

This is working fine but now we want the payloads to be using Confluent Avro

Is there a way I can have a single Job instance listening to multiple topics with avro schema?

**Comment by cerveada** [comment]
Hi,

Abris is able to convert an avro column inside a dataframe. If you have multiple topics you can read them into multiple dataframes and just repeat the same thing multiple times. I don't see a problem in that. 

Only possible problem can be when you have a dataframe with avro data rows that have incompatible schemas. In that case you must sort the avro data so that all rows in one data frame have compatible schema before you convert them from avro. This can be done by key or just don't mix the schemas at first place - meaning have all schemas in one topic compatible.
