### ISSUE TITLE
schema-registry-clients 5.5 breaks compatibility

### ISSUE THREAD

**Issue by edwardcapriolo** [AbsaOSS/ABRiS#215]
https://github.com/confluentinc/schema-registry/blob/v5.3.1/client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/Schema.java#L28

https://github.com/confluentinc/schema-registry/blob/master/client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/Schema.java#L42

The changes are not readily compatible.

Should this project do a cross build and release for multiple versions of schema registry?

**Comment by edwardcapriolo** [comment]
Check out #216  I have not gotten to try it in an integration test yet but it looks good.

**Comment by kevinwallimann** [comment]
Hi @edwardcapriolo Thanks for your question. Unfortunately, we are currently unable to upgrade to Schema registry v5.4+, because it is incompatible with Spark until version 3.1.x. At runtime, there will be a `NoSuchFieldError`. As explained in #165, the incompatibility issue for Confluent 5.4.0 was introduced by Avro 1.9. We believe the compatibility issue can be resolved with Avro 1.10 which will be supported in Spark 3.2.0 (see https://issues.apache.org/jira/browse/SPARK-27733)

**Comment by edwardcapriolo** [comment]
I had that factory problem.. In my patch I set avro version to <avro.version>1.9.2</avro.version> tests pass.

**Comment by edwardcapriolo** [comment]
Also its a weird issue. As you can see I really did not touch anything related to avro.... I just changed schema registry calls. We can go another route probable and shade/shim this bit. ABRIS does not communicate "avro" its just having a problem talking to a web endpoint, that so happens to be linked against something that so happens to be linked to avro.

**Comment by kevinwallimann** [comment]
Hi @edwardcapriolo Upgrading Avro is indeed the solution, which will be done in Spark 3.2.0 (see https://issues.apache.org/jira/browse/SPARK-27733). Since Avro 1.8 is a dependency of Spark itself, the factory issue will surface when you execute your program with `spark-submit`.

**Comment by edwardcapriolo** [comment]
I will try to shade it. Hving to upgrade all the way to spark 3.2 does not make sense for such a tiny problem.

**Comment by kevinwallimann** [comment]
Let us know if you find any way to make it work.

**Comment by kevinwallimann** [comment]
Closed due to inactivity
