### ISSUE TITLE
For struct objects Abris generates schema where class names clash with package names

### ISSUE THREAD

**Issue by edwardcapriolo** [AbsaOSS/ABRiS#220]
We have a deeply nested structure. { payload: { thisthing:{ ....

Abris ends up generating
type: record
name: payload
namespace: abc
fields [ 

   type:record
   name:thisthing
   namespace: abc.payload.
   
   When you try to avro compile this yinto java classes you get problems with "package collides with type" 
   
   What to do?

**Comment by edwardcapriolo** [comment]
I ended up forking avro-schema-utils and changed this:
https://github.com/apache/spark/blob/master/external/avro/src/main/scala/org/apache/spark/sql/avro/SchemaConverters.scala#L188

val childNameSpace = if (nameSpace != "") s"$nameSpace.$recordName" else recordName

to

val childNameSpace = if (nameSpace != "") s"$nameSpace.$recordNameaddingstuffhere" else recordName

schema compiles

**Comment by kevinwallimann** [comment]
Hi @edwardcapriolo Thanks for sharing this observation. As you've already noticed, ABRiS relies on Spark for schema generation. Basically, ABRiS only provides wrapper methods to the `SchemaConverters` implementation. Therefore, unfortunately, this is not something we can fix in ABRiS. In your custom implementation, maybe you could try to uppercase the record names if you don't want to change the namespace

**Comment by edwardcapriolo** [comment]
@kevinwallimann  I solved this by simply copying the single method from SchemaConverter and making the change above.

**Comment by kevinwallimann** [comment]
@edwardcapriolo I agree, this seems to be a common use case and I'm a bit surprised that we haven't received similar feedback earlier from other users. It's true that `SchemaConverters` is not the definitive way. However, it's a default that apparently works for most cases. Thus, we want to build upon that basic implementation, rather than implement our own version of what we think is a sensible schema conversion. In fact, there may be no definitive way how to create an Avro schema from a spark schema (e.g. how to deal with default values). For that reason, you can always register your own schema. So I wouldn't say that Abris is unusable for Java projects per se.

**Comment by edwardcapriolo** [comment]
Spark now calls SchemaConverters:

@DeveloperApi

 A lower-level, unstable API intended for developers. * * Developer API's might change or be removed in minor versions of Spark.

**Comment by kevinwallimann** [comment]
Closed due to inactivity
