### ISSUE TITLE
Support for per record deserialisation

### ISSUE THREAD

**Issue by kevinkwoncareem** [AbsaOSS/ABRiS#226]
Hi I have a general question about per record deserialisation

Currently, I'm using Spark Streaming and it accumulate records from Kafka processing in microbatches

Problem is that the publisher can evolve their schema and start sending messages anytime, resulting in 2 (or more but not likely since the publisher won't evolve their schema that often) different schema records in single batch.

I'd like to deserialize each record based on their schema in a single batch, and want to know if is this possible

**Comment by cerveada** [comment]
I assume you use confluent Avro format. There will be two types of schema for you. Reader and Writer schema. 

- Reader schema will be constant, because that is the schema that corresponds 1:1 to spark data types and Dataframe cannot have multiple schemas.
-  Writer schema can change. This is the schema that was used by the writer of the Kafka message to encode to Avro. The writer schema can evolve. And in confluent Avro format each row will have a writer schema id at the start of Avro payload.

Abris will find the writer schema for each row and convert the data using the writer and reader schema. There is a condition that the **schemas must be compatible**. Then it should all work just fine.


But, my knowledge about streaming is not very deep. @kevinwallimann can you confirm that it works the way I described?

**Comment by kevinkwoncareem** [comment]
@cerveada Thanks for the answer.
