### ISSUE TITLE
AvroSerdewithKeyColumn does not support NULL key

### ISSUE THREAD

**Issue by mathiassp** [AbsaOSS/ABRiS#31]
We are facing the following issue where we want to write data to Kafka based on partitioning key that can be null. The job crashes because it expects a non nullable key.

Is this expected or behavior or can a pull request be made to change this?

A quick fix for this would be to filter the records with null key at the producer side, but then we don't have any information on how many "data" that is being dropped on the consumer side.
 
Another fix would be to replace the null value with a wildcard or hash to keep everything evenly partitioned, but this is also not desired behavior. 

Is there a possibility to change the toConfluentAvroWithPlainKey() in order for it to allow nullable keys?

Thanks!

**Comment by felipemmelo** [comment]
Hi Mathias,

Thanks for reporting. 

Initially it was intended by design, i.e. keys are expected in the API that supports them.

Right now I'm a little bit out of time to dive into this issue, however, if you have ideas about solutions and want to submit PRs, I'm more than happy in collaborating. What do you think?

Cheers.

**Comment by cerveada** [comment]
With the new API (Abris 3.x.x) you should have much more control over the data frame and this should be easily handled outside of Abris.

Feel free to reopen if you still feel there is a problem.
