### ISSUE TITLE
how can we write data frame to multiple avro Kafka topics ?

### ISSUE THREAD

**Issue by abhisam** [AbsaOSS/ABRiS#32]
i want to write dataframe to multiple topics

**Comment by felipemmelo** [comment]
Hello @abhisam ,

To make sure I understood your question, would you like to register the schema for the same dataframe into multiple Schema Registry topics and then dispatch that dataframe to those topics?

Cheers.

**Comment by abhisam** [comment]
Hi @felipemmelo ,
 i want to write a data frame to multiple topic based on conditions. can we write that in single write stream ?

**Comment by felipemmelo** [comment]
Hi @abhisam , I'm not sure structure streams allow it. From the library perspective there should be no problem, since it only encodes the payload for you. I'll check if Spark itself allows it.

Also, if I'm not mistaken, since Spark 2.4 there is a new API called `foreachBatch` or something like this. Have you tried any of these options without ABRiS, to see if it is allowed by Spark?

**Comment by abhisam** [comment]
i am using spark 2.3.  i didn't try spark 2.4 . is it possible to do in 2.3?

**Comment by felipemmelo** [comment]
I don't think it is possible to do this using Structured Streaming.
